// Server-side view of the vendored models.dev snapshot
// (pydexpi_datalog/llm/model_catalog.json, regenerated by
// scripts/refresh_model_catalog.py). The Python backend reads the same file,
// so there is one catalogue and no chance of the two drifting.
//
// The snapshot is ~500 KiB, far too large to hand to the browser wholesale.
// The page fetches a compact provider index and then one provider's models at
// a time.

import { readFileSync } from "node:fs";
import { resolve } from "node:path";

export type CatalogModel = {
  id: string;
  name: string;
  context: number | null;
  reasoning: boolean;
  released: string;
};

export type CatalogProvider = {
  name: string;
  wire: "openai" | "anthropic" | "gemini";
  base_url: string;
  env_var: string;
  doc: string;
  models: CatalogModel[];
  is_local?: boolean;
};

export type ByokCatalog = {
  featured: string[];
  providers: Record<string, CatalogProvider>;
};

export type ProviderIndexEntry = {
  id: string;
  name: string;
  doc: string;
  modelCount: number;
  isLocal: boolean;
};

export type ProviderSettings = { provider: string; model: string; credential: string };

// Provider ids this app shipped before adopting models.dev naming.
const PROVIDER_ALIASES: Record<string, string> = { gemini: "google" };

// Local model servers are not in the hosted snapshot: their endpoint and model
// set belong to the operator's machine. Mirrors _local_providers() in
// pydexpi_datalog/llm/model_catalog.py.
const LOCAL_PROVIDERS: Record<string, CatalogProvider> = {
  ollama: {
    name: "Ollama (local)",
    wire: "openai",
    base_url: process.env.OLLAMA_BASE_URL || "http://localhost:11434/v1",
    env_var: "OLLAMA_BASE_URL",
    doc: "https://docs.ollama.com",
    models: [],
    is_local: true,
  },
};

let cached: ByokCatalog | null = null;

function catalogPath() {
  // Next runs with cwd=frontend; the snapshot lives beside the Python package.
  return resolve(process.cwd(), "..", "pydexpi_datalog", "llm", "model_catalog.json");
}

export function loadByokCatalog(): ByokCatalog {
  if (cached) return cached;
  const raw = JSON.parse(readFileSync(catalogPath(), "utf-8")) as {
    featured: string[];
    providers: Record<string, CatalogProvider>;
  };
  cached = {
    featured: raw.featured,
    providers: { ...LOCAL_PROVIDERS, ...raw.providers },
  };
  return cached;
}

export function resolveProviderId(provider: string): string {
  return PROVIDER_ALIASES[provider] ?? provider;
}

export function catalogProvider(provider: string): CatalogProvider | null {
  return loadByokCatalog().providers[resolveProviderId(provider)] ?? null;
}

/** Featured providers first, then the long tail alphabetically. */
export function providerIndex(): ProviderIndexEntry[] {
  const catalog = loadByokCatalog();
  const featured = catalog.featured.filter((id) => catalog.providers[id]);
  const rest = Object.keys(catalog.providers)
    .filter((id) => !featured.includes(id))
    .sort();
  return [...featured, ...rest].map((id) => {
    const provider = catalog.providers[id];
    return {
      id,
      name: provider.name,
      doc: provider.doc,
      modelCount: provider.models.length,
      isLocal: provider.is_local === true,
    };
  });
}

export function providerModels(provider: string): CatalogModel[] {
  return catalogProvider(provider)?.models ?? [];
}

/**
 * Validate a provider-settings payload that arrived from the browser. Keys are
 * held client-side, so the turn route receives them as untrusted request data;
 * anything the backend would reject is dropped here, letting the caller fall
 * back to server-side configuration.
 */
export function validateProviderSettings(value: unknown): ProviderSettings | null {
  if (typeof value !== "object" || value === null) return null;
  const record = value as Record<string, unknown>;
  if (typeof record.provider !== "string") return null;

  const provider = resolveProviderId(record.provider);
  const catalogued = catalogProvider(provider);
  if (!catalogued) return null;

  const model = typeof record.model === "string" ? record.model.trim() : "";
  if (!model) return null;

  const credential = typeof record.credential === "string" ? record.credential.trim() : "";
  // A local server needs no credential; everything else does.
  if (!credential && !catalogued.is_local) return null;

  // A local server's models cannot be enumerated ahead of time, so membership
  // stays open. Hosted providers are checked against the snapshot.
  if (!catalogued.is_local && !catalogued.models.some((entry) => entry.id === model)) {
    return null;
  }
  return { provider, model, credential };
}
