"""Provider/model catalogue backing bring-your-own-key model selection.

The data is a vendored snapshot of models.dev (the catalogue pi and opencode
use), regenerated by scripts/refresh_model_catalog.py. Vendoring keeps provider
resolution deterministic and offline-capable; a live fetch would let an
upstream edit change which models a review is allowed to run.

The snapshot is filtered to models advertising native tool calls, so presence
in this catalogue *is* the capability gate that grounded QA depends on --
replacing the hand-maintained provider/model allow-list that preceded it.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path
from typing import Any

_CATALOG_PATH = Path(__file__).with_name("model_catalog.json")

# Provider ids this app shipped before adopting models.dev naming. Stored
# credentials and .env files still use them.
_PROVIDER_ALIASES = {"gemini": "google"}

_OLLAMA_DEFAULT_BASE_URL = "http://localhost:11434/v1"


class UnknownProviderError(ValueError):
    def __init__(self, provider: str) -> None:
        super().__init__(
            f"unsupported model provider: {provider}. "
            "See scripts/refresh_model_catalog.py for the supported set."
        )
        self.provider = provider


class UnknownModelError(ValueError):
    def __init__(self, provider: str, model: str) -> None:
        super().__init__(
            f"{provider} does not serve a native-tool-capable model named {model!r}."
        )
        self.provider = provider
        self.model = model


@dataclass(frozen=True)
class CatalogModel:
    id: str
    name: str
    context: int | None = None
    reasoning: bool = False
    released: str = ""


@dataclass(frozen=True)
class CatalogProvider:
    id: str
    name: str
    wire: str
    base_url: str
    env_var: str
    doc: str = ""
    models: dict[str, CatalogModel] = field(default_factory=dict)
    # A local model server serves whatever the operator has pulled, so its
    # model set cannot be snapshotted and membership stays open.
    is_local: bool = False


@dataclass(frozen=True)
class Catalog:
    featured: tuple[str, ...]
    providers: dict[str, CatalogProvider]


def _local_providers() -> dict[str, CatalogProvider]:
    """Local model servers, which are not in the hosted catalogue because their
    endpoint and model set belong to the operator's machine."""

    return {
        "ollama": CatalogProvider(
            id="ollama",
            name="Ollama (local)",
            wire="openai",
            base_url=os.environ.get("OLLAMA_BASE_URL") or _OLLAMA_DEFAULT_BASE_URL,
            env_var="OLLAMA_BASE_URL",
            doc="https://docs.ollama.com",
            is_local=True,
        )
    }


@lru_cache(maxsize=1)
def load_catalog() -> Catalog:
    raw: dict[str, Any] = json.loads(_CATALOG_PATH.read_text())
    providers = dict(_local_providers())
    for provider_id, provider in raw["providers"].items():
        providers[provider_id] = CatalogProvider(
            id=provider_id,
            name=provider["name"],
            wire=provider["wire"],
            base_url=provider["base_url"],
            env_var=provider["env_var"],
            doc=provider.get("doc", ""),
            models={
                model["id"]: CatalogModel(
                    id=model["id"],
                    name=model["name"],
                    context=model.get("context"),
                    reasoning=bool(model.get("reasoning")),
                    released=model.get("released", ""),
                )
                for model in provider["models"]
            },
        )
    return Catalog(featured=tuple(raw["featured"]), providers=providers)


def resolve_provider_id(provider: str) -> str:
    """Map a possibly-legacy provider id onto its catalogue id."""

    return _PROVIDER_ALIASES.get(provider, provider)


def catalog_provider(provider: str) -> CatalogProvider:
    found = load_catalog().providers.get(resolve_provider_id(provider))
    if found is None:
        raise UnknownProviderError(provider)
    return found


def catalog_model(provider: str, model: str) -> CatalogModel:
    found = catalog_provider(provider)
    if found.is_local:
        if not model:
            raise UnknownModelError(provider, model)
        return CatalogModel(id=model, name=model)
    catalogued = found.models.get(model)
    if catalogued is None:
        raise UnknownModelError(provider, model)
    return catalogued


def is_catalogued_model(provider: str, model: str) -> bool:
    try:
        catalog_model(provider, model)
    except (UnknownProviderError, UnknownModelError):
        return False
    return True


def featured_provider_ids() -> list[str]:
    return list(load_catalog().featured)


def provider_summaries() -> list[dict[str, Any]]:
    """Catalogue projection for the API-keys picker: featured providers first,
    then the long tail alphabetically."""

    catalog = load_catalog()
    featured = featured_provider_ids()
    ordered = featured + sorted(pid for pid in catalog.providers if pid not in featured)
    return [
        {
            "id": provider.id,
            "name": provider.name,
            "env_var": provider.env_var,
            "doc": provider.doc,
            "is_local": provider.is_local,
            "models": [
                {
                    "id": model.id,
                    "name": model.name,
                    "context": model.context,
                    "reasoning": model.reasoning,
                    "released": model.released,
                }
                for model in provider.models.values()
            ],
        }
        for provider in (catalog.providers[pid] for pid in ordered)
    ]
